### ISSUE TITLE
Refactor playground

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/playground#1]
## Overview

As more features are added I think a vanilla.js-based implementation would become more cumbersome and difficult to maintain. So we plan to refactor the playground based on `Vue` framework 

## Tasks

- [ ] Refactor playground based on `Vue` framework
- [ ] Replace the current CodeMirror editor with [Monaco](https://github.com/microsoft/monaco-editor).
- [ ] Support for transformer configuration editing. Learn more oxc-project/oxc#2709 

## Possible Tasks

- Linter rules configuration
- ..

## Playground Design

Since we don't have a designer, we can't design a nice playground, but instead, maybe we can use [shadcn-vue](https://www.shadcn-vue.com/) and utility-first CSS framework for `UnoCSS` or `TailwindCSS` to help us build it quickly. Or ask AI at https://www.vue0.dev/

## Expected Outcome

By the end of this refactor, the OXC Playground should be more user-friendly and maintainable. The switch to Vue and Monaco should provide a better development experience.

## Reference
- https://github.com/sxzz/ast-explorer AST Explorer, Use Vue and [Monaco](https://github.com/microsoft/monaco-editor)
- https://play.swc.rs/ SWC Playground
- https://biomejs.dev/playground/ Biome Playground

**Comment by Boshen** [comment]
I will get the wasm thing compiling and integrate once we have vite running.

**Comment by eryue0220** [comment]
Could I get the first one? I can help to rewrite it based on `vite` and `vue`.

**Comment by eryue0220** [comment]
> > Could I get the first one? I can help to rewrite it based on `vite` and `vue`.
> 
> Of course. Can you PR in smaller commits to make things easier to review?

Yes, sure.

**Comment by Boshen** [comment]
I added the wasm build and build instruction https://github.com/oxc-project/playground/commit/70800839a3ab2ef4479e3404a5936bb161544ed6

**Comment by Boshen** [comment]
@eryue0220, @leaysgur is looking into continuing the work, please let us know if you have made further progress.

**Comment by eryue0220** [comment]
> @eryue0220, @leaysgur is looking into continuing the work, please let us know if you have made further progress.

Sorry for the late response. I'm currently working on the view editor.

**Comment by Boshen** [comment]
All done by sxzz, tracking transformer tab in https://github.com/oxc-project/playground/issues/25
